import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import HeaderSection from "@/components/headerSection";
import { ImageContext } from "@/components/contextApi/imageContext";
import { useState } from "react";
import ImageProvider from "@/components/contextApi/imageProvider";
import Register from "@/components/registeration";
import NavBar from "@/components/navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WoPond",
  description: "Generated by BawdicSoft",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-4PTWWCK24E"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-4PTWWCK24E');
            `,
          }}
        />
      </Head>
      <body className={inter.className}>
        <ImageProvider>
          <div className="bg-black">
            <NavBar />
          </div>

          {/* <HeaderSection /> */}
          <Register />
          {children}
          <Footer />
        </ImageProvider>
      </body>
    </html>
  );
}
