import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import HeaderSection from "@/components/headerSection";
import { ImageContext } from "@/components/contextApi/imageContext";
import { useState } from "react";
import ImageProvider from "@/components/contextApi/imageProvider";
import Register from "@/components/registeration";
import NavBar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WooPond",
  description: "Generated by BawdicSoft",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ImageProvider>
       <div className="bg-black"><NavBar />
        </div> 

          {/* <HeaderSection /> */}
          <Register />
          {children}
          <Footer />
        </ImageProvider>
      </body>
    </html>
  );
}
